DROP TABLE IF EXISTS informations_user;
DROP TABLE IF EXISTS profil;

CREATE TABLE IF NOT EXISTS informations_user(
    id INTEGER PRIMARY KEY, 
    role_user INTEGER DEFAULT 1 CHECK (role_user BETWEEN 1 AND 3),
    pseudo VARCHAR(255) NOT NULL,
    mail VARCHAR(255) NOT NULL,
    mdp VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS connexion(
    pseudo VARCHAR(255) NOT NULL,
    mdp VARCHAR(255) NOT NULL
);